# Generated by Django 5.2.3 on 2025-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0005_alter_brand_description_alter_brand_logo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='web_site',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
