# Generated by Django 5.2.3 on 2025-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0008_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
