# Generated by Django 5.2.3 on 2025-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0009_alter_products_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_prod',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='img_prod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
