# Generated by Django 5.2.3 on 2025-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0010_alter_img_prod_created_ad_alter_img_prod_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_prod',
            name='img_path',
            field=models.ImageField(max_length='1000', upload_to=''),
        ),
    ]
