# Generated by Django 5.2.3 on 2025-06-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=1000)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_desyra.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('paid', 'Pagato'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato')], default='pending', max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Non pagato'), ('paid', 'Pagato')], default='unpaid', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(db_column='id_address', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core_desyra.shipping_address')),
                ('shipping', models.OneToOneField(db_column='id_shipping', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core_desyra.shipping')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core_desyra.users')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('stock_aviability', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_brand', models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='core_desyra.brand')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_desyra.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_desyra.products')),
            ],
        ),
        migrations.CreateModel(
            name='Img_prod',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('alt_text', models.CharField(max_length=15)),
                ('is_main_img', models.BooleanField(default=False)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img_path', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core_desyra.products')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id_variant', models.AutoField(primary_key=True, serialize=False)),
                ('cod_variant', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_aviability', models.IntegerField()),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='core_desyra.products')),
            ],
        ),
        migrations.CreateModel(
            name='Chart_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitaty', models.IntegerField()),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=4)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.ForeignKey(db_column='id_chart', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_desyra.chart')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='product_chart', to='core_desyra.products')),
            ],
            options={
                'unique_together': {('chart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Category_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='core_desyra.category')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core_desyra.products')),
            ],
            options={
                'unique_together': {('category', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitaty', models.IntegerField()),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=4)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core_desyra.products')),
                ('wishlist', models.ForeignKey(db_column='id_wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_desyra.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
