# Generated by Django 5.2.3 on 2025-06-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0003_alter_users_name_alter_users_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chart',
            field=models.OneToOneField(db_column='id_chart', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_desyra.chart'),
        ),
        migrations.AlterField(
            model_name='users',
            name='shipping_address',
            field=models.ForeignKey(db_column='id_address', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_desyra.shipping_address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='wishlist',
            field=models.OneToOneField(db_column='id_wishlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_desyra.wishlist'),
        ),
    ]
