# Generated by Django 5.2.3 on 2025-07-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0004_alter_users_chart_alter_users_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='web_site',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id_brand',
            field=models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core_desyra.brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
