# Generated by Django 5.2.3 on 2025-07-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0011_alter_img_prod_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_prod',
            name='category',
            field=models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_img', to='core_desyra.category'),
        ),
    ]
