# Generated by Django 5.2.3 on 2025-07-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0012_img_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_prod',
            name='product',
            field=models.ForeignKey(blank=True, db_column='id_product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core_desyra.products'),
        ),
    ]
