services:
  db:
    image: mysql:8.0
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s 
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ../back_end_desyra/app/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net

  be:
    build: ../back_end_desyra/app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    #bindo porta nella ci perche tento di raggiongere un endpoint tramite il runner
    ports:
      - "8000:8000"
    networks:
      - db_net

volumes:
  mysql_data:

networks:
  db_net: