services:
  db:
    image: mysql:8.0
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./desyra/back_end_desyra/app/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net

  be:
    build: ../back_end_desyra/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - db_net

volumes:
  mysql_data:

networks:
  db_net: