# Generated by Django 5.2.3 on 2025-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_desyra', '0006_alter_brand_description_alter_brand_logo_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
